name: rich_clipboard_macos
description: macOS implementation of the rich_clipboard plugin.
homepage: https://github.com/fegea-immo/rich_clipboard_macos
repository: https://github.com/fegea-immo/rich_clipboard_macos
version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  rich_clipboard_platform_interface: ^1.0.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: rich_clipboard
    platforms:
      macos:
        pluginClass: RichClipboardPlugin
        dartPluginClass: MethodChannelRichClipboard
